inputVatly= prompt("Nhập điểm Vật Lý: ");
inputHoahoc= prompt("Nhập điểm Học Hóa: ");
inputSinhhoc= prompt("Nhập điểm Sinh Học");
var vatLy= parseFloat(inputVatly);
var sinhHoc= parseFloat(inputSinhhoc);
var hoaHoc= parseFloat(inputHoahoc);
var tongDiem= vatLy+hoaHoc+sinhHoc;
var dtb= tongDiem/3;
document.write("Tổng điểm là : " +tongDiem);
document.write("<br>");
document.write("Điểm trung bình là : " +dtb);
